
CONFIG_FILE = "config.cfg"

ACCESS_KEY = 'ACCESS_KEY'
SECRET_KEY = "SECRET_KEY"
USER = "IAM"

DB = "DB"
INSTANCE_ID = "DB_INSTANCE_ID"
DB_NAME = "DB_NAME"
DB_USERNAME = "DB_USERNAME"
DB_PASSWORD = "DB_PASSWORD"
PORT = "DB_PORT"
INSTANCE_CLASS = "db.t3.micro"
ENGINE = "postgres"
ALLOC_STORAGE = 20